### PR TITLE
Snaps (CI Failing)

### PR DESCRIPTION
**Pull request by kenneth-reitz**

### CODE REVIEW

**Comment by kenneth-reitz** [comment]
@wilzbach `docker: Error response from daemon: pull access denied for story-snapcraft, repository does not exist or may require 'docker login'.`

**Comment by wilzbach** [comment]
Yeah CircleCi imposes severe restrictions on Docker that's why I paused this for now. I will be a lot easier to get this working on TravisCI which I will do once I get around (probably during the team summit).

**Comment by anukul** [comment]
I think we can even use CircleCI for this purpose - https://circleci.com/docs/2.0/building-docker-images

**Comment by judepereira** [comment]
Closing in favour of #218.

**Pull request closed without merging**
