### PR TITLE
Rename 'story write' to 'story template'

### LINKED ISSUE #225: Rename `story write` to `story example`
- `story write` is a pretty bad name for templates
- imho it should be `example` or `template`

### PR DESCRIPTION
**Pull request by darkLord19**
Fixes #225

### CODE REVIEW

**Comment by darkLord19** [comment]
@wilzbach sure I will update docs as well

**Comment by darkLord19** [comment]
@judepereira okay sure I will update PR with changes

**Comment by darkLord19** [comment]
@judepereira Should I create write as an alias to template command or should I copy the old write.py and add write command separately with the deprecation warning?

**Comment by judepereira** [comment]
@darkLord19 Create it as an alias :)

**Comment by darkLord19** [comment]
@judepereira Check this out

**Comment by judepereira** [comment]
@darkLord19 Looks good. Can you please add tests to ensure that the old command works too?

**Comment by darkLord19** [comment]
@judepereira can you tell me how? I mean I tested commands manually and they are working so how and what kind of tests I create for this?

**Comment by judepereira** [comment]
@darkLord19 Looks like there's no way to do so in code itself. What you can do for now - add the following to the circleCI testing pipeline:
1. story write http > http_from_write.story
2. story template http > http_from_template.story
3. if contents of http_from_write.story != contents of http_from_template.story - throw an error, fail the CI test.

**Pull request merged**
