### PR TITLE
Add basic shell completion

### PR DESCRIPTION
**Pull request by anukul**
Shell completion can be enabled by one of two ways:

- Run `$ asyncy completion show`, execute the command(s) it prints
- Run `$ asyncy completion install` and restart your shell

### CODE REVIEW

**Comment by wilzbach** [comment]
We have a similar issue for Storyscript (https://github.com/storyscript/storyscript/issues/737).
It also uses `click`.

**Comment by judepereira** [comment]
@anukul can you update this PR?

**Comment by kenneth-reitz** [comment]
Can we change this to `story completion --install` and just `story completion`, which outputs the completion code?

**Comment by anukul** [comment]
Yes, I'll update this later today / tomorrow.

**Comment by anukul** [comment]
__Approach 1__: When `$ story completion` is a click command and `--install` is a click option / flag (what you suggested)
- Options are only visible in the help text.
The completion library does not start suggesting options (`--install`) before the user enters a hyphen, so it's difficult to convey that this exists.
```
$ story completion --help
Usage: story completion [OPTIONS] [[bash|fish|zsh|powershell]] [PATH]

  Show or install shell completion code

Options:
  -i, --case-insensitive / --no-case-insensitive
                                  Case insensitive completion
  --install                       Install completion code into shell startup
                                  file
  --append / --overwrite          Append the completion code to the file
  --help                          Show this message and exit.
```

- If one were to type `story completion <tab>` (no hyphens before tabbing), they would see choices for the `shell` argument.
```
$ story completion <tab>
bash        -- Bourne again shell
fish        -- Friendly interactive shell
powershell  -- Windows PowerShell
zsh         -- Z shell
```
If we choose to go with this though, I can discuss showing flags in completion without a necessary hyphen (perhaps on a per flag basis) in their repo in an issue, or add it in our own fork of the project (?).

---
__Approach 2__: When `$ story completion` is a click group (I followed this from a click-contrib/completion [example](https://github.com/click-contrib/click-completion/blob/master/examples/click-completion-command))
- `show` and `install` are now subcommands, both of them are shown in completion and ommitting both prints the help text
```
$ story completion --help
Usage: story completion [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  install  Install the click-completion-command completion
  show     Show the click-completion-command completion code
```
This also now helps organize `--append / --overwrite` into click options only applicable to the `install` subcommand.

---
__Approach 3__: When `$ story --completion` is a flag, and the installation option is absent.
Also the shell is automatically detected, and cannot be overriden using a `shell` click argument.
I'm not sure if a `--shell` click option makes sense here either.
This is followed in pipenv
```
$ story --help
Usage: story [OPTIONS] COMMAND [ARGS]...

  Hello! Welcome to Storyscript.

  We hope you enjoy, & we look forward to your feedback!

  Documentation: https://docs.storyscript.io/

Options:
  --completion  Show code for shell completion
  --help        Show this message and exit.

Commands:
  apps         Create, list, and manage apps on Storyscript Cloud.
  ...
```

Let me know what seems most appropriate.

**Comment by anukul** [comment]
Ready for review!

**Comment by kenneth-reitz** [comment]
Looks good!

**Comment by kenneth-reitz** [comment]
:sparkles: :cake: :sparkles:

**Pull request merged**
