### PR TITLE
Add containerconfig command

### PR DESCRIPTION
**Pull request by anukul**
Adds the following commands:

```
$ story containerconfig list
$ story containerconfig create <name> <path_to_json> --team <team_name>
$ story containerconfig update <name> <path_to_json>
$ story containerconfig get <name>
$ story containerconfig delete <name>
```

Related:
- https://github.com/storyscript/platform-engine/issues/299
- https://github.com/storyscript/database/pull/72

### CODE REVIEW

**Comment by anukul** [comment]
`$ story dockercfg update <name> <path_to_json>` always returns
```
Error: No values were updated in collection 'owner_dockercfgs' because no values you can update were found matching these criteria.
```
Can someone please check what's wrong? I can't seem to figure it out at the moment.

**Comment by kenneth-reitz** [comment]
can we call this `docker-config` or `dockerconfig` instead?

**Comment by anukul** [comment]
@kenneth-reitz Changed the command name.
Wrt tests, I'm trying to mock the API calls, but the CLI fixture currently uses `delegator` to invoke commands in a subprocess, and I don't think mocks works in that case.
How do I proceed?

**Comment by anukul** [comment]
@kenneth-reitz Changed the command name.
Wrt tests, I'm trying to mock the API calls, but the CLI fixture currently uses `delegator` to invoke commands in a subprocess, and I don't think mocks works in that case.
How do I proceed - only writing end to end tests, or using a separate CLI fixture for unit tests?

P.S. Do we want end to end tests in the CLI? It seems kinda weird that they use the prod db, even though the operations could possibly be reversed (create -> delete)

**Comment by anukul** [comment]
@kenneth-reitz Changed the command name.
Wrt tests, I'm trying to mock the API calls, but the CLI fixture currently uses `delegator` to invoke commands in a subprocess, and I don't think mocks works in that case.
How do I proceed - only writing end to end tests, or using a separate CLI fixture for unit tests?

P.S. It seems kinda weird that tests use the prod db, even though the operations could possibly be reversed (create -> delete)

**Comment by kenneth-reitz** [comment]
We're doing integration tests, at this point, which ensures that the user experience is 100% at all times.

**Comment by kenneth-reitz** [comment]
At Heroku, we needed to have permission to use the word `docker` in our product. Is `container` potentially more appropriate?

**Comment by judepereira** [comment]
@kenneth-reitz makes sense. @anukul use container.

**Comment by anukul** [comment]
Changed `dockerconfig` to `containerconfig` and added tests to cover all commands.
I'll update here when the RLS policy for updates is fixed.

**Comment by anukul** [comment]
Ready for review!

**Comment by kenneth-reitz** [comment]
Hmm, those are both not good names :)

Does this need to be a top-level command? Can we make it `$ story container login`?

**Comment by kenneth-reitz** [comment]
or perhaps `$ story container authorize`.

**Comment by judepereira** [comment]
@kenneth-reitz we need to satisfy the following:
```
$ story containerconfig list
$ story containerconfig create <name> <path_to_json> --team <team_name>
$ story containerconfig update <name> <path_to_json>
$ story containerconfig get <name>
$ story containerconfig delete <name>
```

**Comment by kenneth-reitz** [comment]
I'd like to see it be called `story containers`. What exactly is this doing?

**Comment by anukul** [comment]
@kenneth-reitz Through this command, users upload docker credentials for use by storyscript cloud to pull images from private repositories.

**Comment by kenneth-reitz** [comment]
I really like `$ story container login`

**Comment by wilzbach** [comment]
Ask this is just about docker, have we tried asking for permission as it would be a lot clearer.

**Comment by anukul** [comment]
> I really like `$ story container login`

@kenneth-reitz Since this is a config management process, we'll probably need CRUD verbs, similar to what's in the PR description.

**Comment by kenneth-reitz** [comment]
Closing for #205

**Pull request closed without merging**
