### PR TITLE
WIP - App name should be at least 4 chars

### PR DESCRIPTION
**Pull request by anukul**
Conforming to the similar database validation rule

### CODE REVIEW

**Comment by stevepeak** [comment]
@anukul Thanks for the pull! Can you provide the unittests for this addition? We need to pump up the unittests on this project in general.

**Comment by anukul** [comment]
@stevepeak Sure, I'm a bit occupied with college exams this week. I'll add tests for this and other functions as soon as they're over.

**Comment by anukul** [comment]
@stevepeak For the tests, I'm planning to use [`unittest.mock`](https://docs.python.org/3/library/unittest.mock.html) to mock the user authentication checks, API calls and other external logic triggered by the `$ asyncy apps create` command.

Does that approach sound good, or should we follow something else?

**Comment by kenneth-reitz** [comment]
closing due to merge conflicts. I'll add this by hand, though.

**Pull request closed without merging**
