### PR TITLE
Rename main.py to __main__.py

### LINKED ISSUE #297: __main__ support
Most CLI applications can be executed using `-m` ([pep](https://www.python.org/dev/peps/pep-0366/))
```
$ python3 -m story
/usr/bin/python3: No module named story.__main__; 'story' is a package and cannot be directly executed
```

This is especially useful for testing, as it allows access using `['sys.executable', '-m', 'story']` avoiding all of the setuptools/pkg_resources stuff which is extremely slow and also can invoke a different runtime the one being tested if there are multiple runtimes on the test worker.

### PR DESCRIPTION
**Pull request by arturtamborski**
This pull request renames `main.py` to `__main__.py` allowing user to run the application as a python module.
Fixes #297

### CODE REVIEW

**Comment by judepereira** [comment]
Thanks @arturtamborski!

**Comment by jayvdb** [comment]
G'day @arturtamborski , thanks for quickly fixing the issue I raised yesterday.

btw, did you find my issue via the label "good first issue" or other service such as https://www.firsttimersonly.com/ , or are you playing around with Storyscript?

https://github.com/storyscript/cli/issues/303 is a follow up issue if you are interested.

**Comment by arturtamborski** [comment]
Hi, I found it on [goodfirstissue](https://twitter.com/goodfirstissue). This project appeared there quite a few times and looked to me like a cool place to start working on something new :)

**Comment by williammartin** [comment]
Awesome, thanks @arturtamborski, you're very welcome and thanks for your contribution. If you have any questions or concerns, please get in touch.

**Pull request merged**
