### PR TITLE
Show steps taken during deployment

### LINKED ISSUE #190: Show the magic!
# Show the magic of deployment! 

d7c0acp-74dd66df-9f43-44aa-aabb-c9abc442af4c

## Ideas
- Where is it deployed (what region/cloud provider).
- How was it deployed (Kubernetes)
- How many containers were orchestrated?
- How many functions where packaged?
- Subscribing ingress/pubsub?

This feeds into `story inspect` command and a command to expose the k8s configurations.

A couple customers have asked the questions above. It will be important to expose the key data and add a `-v/--verbose` flag to show much more magic.

:sparkles::cake::sparkles:

### PR DESCRIPTION
**Pull request by williammartin**
Opening up discussion on this client-side solution, simply outlining the steps that were taken as part of an app deployment. Something we can iterate on as we see what people respond to regarding:
 - liveliness output
 - information that appears in the output
 - dynamism depending on the app itself

Screenshot of how this looks for the story:

```
http server as server
    when server listen method: "get" path: "/" as r
        out = base64 encode content:"foo"
        r write content:out
```

image

[fixes #190]

### CODE REVIEW

**Comment by judepereira** [comment]
@williammartin Can we print the story names?
```
Compiling Stories… 
✔ Compiled 3 stories

Deploying app dazzling-nobel-9115... 
✔ Version 148 of your app has been queued for deployment.

Waiting for deployment to complete…  
✔ Configured 3 stories
✔ Deployed 2 services
  - http
  - log
✔ Created ingress route
✔ Configured logging
✔ Configured health checks
✔ Deployment successful!

To see your app's logs, please run:
  story logs -f

If your Story responds to HTTP requests, please visit:
  https://dazzling-nobel-9115.storyscriptapp.com/

Process finished with exit code 0
```

**Comment by williammartin** [comment]
@judepereira Donezo:

image

**Comment by judepereira** [comment]
Thanks! I'll run a quick test and merge.

**Comment by judepereira** [comment]
LGTM. Merging and releasing the CLI.

**Pull request merged**
