### PR TITLE
config list --shell

### PR DESCRIPTION
**Pull request by kenneth-reitz**
Also, sort the keys, so they are in alphabetical order (not the order in which they were set).

### CODE REVIEW

**Comment by kenneth-reitz** [comment]
Ready for review.

**Comment by judepereira** [comment]
How will service variables and Storyscript variables look like the shell mode? A preview output?

**Comment by kenneth-reitz** [comment]
`twitter.SERVICE_VAR='1'`. This is a valid environment variable name, I believe.

**Comment by kenneth-reitz** [comment]
Ah, nice catch.

**Comment by kenneth-reitz** [comment]
That is not a valid identifier. 

Will have to update this.

**Comment by kenneth-reitz** [comment]
perhaps this isn't the best feature for us, because of this.

**Pull request closed without merging**
